Frontend:  # Frontend processor (instruction issue) configuration
  impl: SimpleO3  # Uses SimpleO3 (simple out-of-order execution) frontend
  clock_ratio: 8  # Clock ratio (frontend vs memory system), indicating the frontend clock is 8x the base clock
  num_expected_insts: 500000  # Expected number of instructions to execute (can be used as a simulation termination condition)
  traces:  # Instruction trace file(s) used to simulate the instruction stream
    - user_trace.trace  # Specifies a trace file to simulate program instruction execution

  Translation:  # Address translation module (virtual address → physical address)
    impl: RandomTranslation  # Uses random address translation strategy
    max_addr: 2147483648  # Sets maximum address space (2GB, i.e., 2^31 bytes of virtual address space)

MemorySystem:  # Memory system configuration
  impl: GenericDRAM  # Uses generic DRAM model
  clock_ratio: 3  # Clock ratio (memory system vs processor), memory clock is 3x the base clock

  DRAM:  # DRAM-related configuration
    impl: HBM3  # Uses HBM3 memory model
    org:  # Organization (specification)
      preset: HBM3_2Gb  # Preset for HBM3_2Gb specification
      channel: 1  # Only one channel
      pseudochannel: 2  # Two pseudochannels per channel
    timing:  # Timing configuration
      preset: HBM3_2Gbps  # Preset for HBM3_2Gbps timing parameters

  Controller:  # DRAM controller configuration
    impl: Generic  # Uses generic controller
    Scheduler:  # Access scheduler
      impl: FRFCFS  # Uses FRFCFS (First Ready First Come First Serve) scheduling strategy
    RefreshManager:  # Refresh manager
      impl: AllBank  # Uses AllBank refresh strategy (refreshes all banks uniformly)
    RowPolicy:  # Row management policy
      impl: OpenRowPolicy  
    plugins:  # Plugin configuration (empty or used for extensions like ECC, prefetchers, etc.)
      - ControllerPlugin:
          impl: ECCPlugin
          data_block_size: 128  # Data block size in bytes
          edc_size: 4  # EDC (error detection code) size in bytes
          ecc_size: 1024  # Maximum ECC size in bytes
          ecc_size: 32  # Maximum usable ECC in bytes
          ecc_type: 'bch'
          edc_type: 'crc32'
          bit_error_rate: 1e-6  # Bit error rate (BER)
          max_failure_prob: 1e-14  # Maximum failure probability

  AddrMapper:  # Address mapping strategy
    impl: RoBaRaCoCh  # Uses RoBaRaCoCh (Row-Bank-Rank-Column-Channel) address mapping method
